name: Flutter无签名IPA打包
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装Flutter环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: latest-stable

      - name: 打包无签名IPA
        run: |
          flutter pub get
          flutter build ipa --no-codesign

      - name: 上传IPA
        uses: actions/upload-artifact@v4
        with:
          name: 无签名IPA
          path: build/ios/ipa/*.ipa
